#pragma once
// Ô¤±àÒëÍ·ÎÄ¼þ
#include <chrono>
#include <cstdio>
#include <iostream>
#include <algorithm>
#include <cmath>
#include <vector>
#include <stack>
#include <list>
#include <bitset>
#include <utility>
#include <deque>
#include <queue>
#include <unordered_map>
#include <unordered_set>
#include <map>
#include <set>
#include <string>
#include <sstream>
#include <functional>
#include <cstdlib>
#include <string.h>
#include <bitset>
#include <tuple>
#include <optional>
#include <variant>
#include <any>
#include <future>
#include <string_view>
#include <mutex>
#include <random>
